"""EV-169 add unique processing step constraint

Revision ID: e383d82daa47
Revises: 6e3ea95d2777
Create Date: 2026-10-09 10:50:01.653311

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e383d82daa47"
down_revision: str | Sequence[str] | None = "6e3ea95d2777"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_processing_steps_job_step", "processing_steps", ["job_id", "step_name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_processing_steps_job_step", "processing_steps", type_="unique"
    )
    # ### end Alembic commands ###
