from enum import StrEnum


class CaseType(StrEnum):
    FRAUD = "FRAUD"
    MONEY_LAUNDERING = "MONEY_LAUNDERING"
    BRIBERY_CORRUPTION = "BRIBERY_CORRUPTION"
    SANCTIONS = "SANCTIONS"
    TERRORIST_FINANCING = "TERRORIST_FINANCING"
    CYBERCRIME = "CYBERCRIME"
    ASSET_MISAPPROPRIATION = "ASSET_MISAPPROPRIATION"
    PROCUREMENT_FRAUD = "PROCUREMENT_FRAUD"
    INSIDER_THREAT = "INSIDER_THREAT"
    COMPLIANCE_REVIEW = "COMPLIANCE_REVIEW"
    INTERNAL_INVESTIGATION = "INTERNAL_INVESTIGATION"
    OTHER = "OTHER"


class CaseStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class CaseRole(StrEnum):
    OWNER = "OWNER"
    INVESTIGATOR = "INVESTIGATOR"
    REVIEWER = "REVIEWER"
    VIEWER = "VIEWER"


class UserSystemRole(StrEnum):
    ADMIN = "ADMIN"
    USER = "USER"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
