from enum import StrEnum


class CaseType(StrEnum):
    FRAUD = "FRAUD"
    MONEY_LAUNDERING = "MONEY_LAUNDERING"
    BRIBERY_CORRUPTION = "BRIBERY_CORRUPTION"
    SANCTIONS = "SANCTIONS"
    TERRORIST_FINANCING = "TERRORIST_FINANCING"
    CYBERCRIME = "CYBERCRIME"
    ASSET_MISAPPROPRIATION = "ASSET_MISAPPROPRIATION"
    PROCUREMENT_FRAUD = "PROCUREMENT_FRAUD"
    INSIDER_THREAT = "INSIDER_THREAT"
    COMPLIANCE_REVIEW = "COMPLIANCE_REVIEW"
    INTERNAL_INVESTIGATION = "INTERNAL_INVESTIGATION"
    OTHER = "OTHER"


class CaseStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class CaseRole(StrEnum):
    OWNER = "OWNER"
    INVESTIGATOR = "INVESTIGATOR"
    REVIEWER = "REVIEWER"
    VIEWER = "VIEWER"


class SystemRole(StrEnum):
    ADMIN = "ADMIN"
    USER = "USER"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class Theme(StrEnum):
    LIGHT = "LIGHT"
    DARK = "DARK"
    SYSTEM = "SYSTEM"


class DefaultLandingPage(StrEnum):
    DASHBOARD = "DASHBOARD"
    CASES = "CASES"
    EVIDENCE = "EVIDENCE"
    AI_INVESTIGATOR = "AI_INVESTIGATOR"


class AIResponseStyle(StrEnum):
    CONCISE = "CONCISE"
    BALANCED = "BALANCED"
    DETAILED = "DETAILED"


class EvidenceProcessingStatus(StrEnum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"


class ProcessingJobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
